version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: annotation-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql-data:
