spring:
  datasource:
    #for docker setup
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    #driver-class-name: com.mysql.cj.jdbc.Driver

    #for local setup
    url: jdbc:mysql://localhost:3306/annotation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: momojojo12345

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  application:
    name: annotation-platform

  mvc:
    static-path-pattern: /**

server:
  port: 8080
